### ISSUE TITLE
Please keep my name in the Author's file

### ISSUE THREAD

**Issue by xstable** [caco3/kim5#8]
Nice that you maintain this package, and you did a fork to let this code get back to live.

As you forked it from my initial work, it would be nice, if you could keep my name in the list of autors and mark it as initial Autor.
I think you also would be glad if people don't remove your name off of an project, they fork?!

**Comment by caco3** [comment]
Hi @xstable 

I guess you refer to the comment I wrote on https://www.pling.com/p/998188/
Indeed it was not very accurate (it was a copy&paste from another comment).
I did NOT clone your repo but instead the original implementation by Charles Bouveyron on https://www.linux-apps.com/p/1126887, from which you also forked your code.
So; no code from you is in my repo.

Beside of this, yes, I fully agree with you, I never would remove any references to other authors!

**Comment by caco3** [comment]
@xstable Since you are not able to provide a response, I will close this "issue"
